# Generated by Django 4.1.4 on 2023-01-02 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("statement", models.TextField(verbose_name="問題文")),
                ("option1", models.CharField(max_length=150, verbose_name="選択肢1")),
                ("option2", models.CharField(max_length=150, verbose_name="選択肢2")),
                ("option3", models.CharField(max_length=150, verbose_name="選択肢3")),
                ("option4", models.CharField(max_length=150, verbose_name="選択肢4")),
                ("option5", models.CharField(max_length=150, verbose_name="選択肢5")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新日")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
            ],
        ),
    ]
