# Generated by Django 4.1.4 on 2023-01-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="answers",
            field=models.IntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                default=1,
                verbose_name="解答番号",
            ),
        ),
    ]
