# Generated by Django 4.1.4 on 2023-01-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0002_quiz_answers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="answers",
        ),
        migrations.AddField(
            model_name="quiz",
            name="answer1",
            field=models.IntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                default=1,
                verbose_name="解答番号1",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="answer2",
            field=models.IntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                null=True,
                verbose_name="解答番号2",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="answer3",
            field=models.IntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                null=True,
                verbose_name="解答番号3",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="answer4",
            field=models.IntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                null=True,
                verbose_name="解答番号4",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="answer5",
            field=models.IntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                null=True,
                verbose_name="解答番号5",
            ),
        ),
    ]
