# Generated by Django 4.1.4 on 2023-01-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0003_remove_quiz_answers_quiz_answer1_quiz_answer2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="answer2",
            field=models.IntegerField(
                blank=True,
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                null=True,
                verbose_name="解答番号2",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="answer3",
            field=models.IntegerField(
                blank=True,
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                null=True,
                verbose_name="解答番号3",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="answer4",
            field=models.IntegerField(
                blank=True,
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                null=True,
                verbose_name="解答番号4",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="answer5",
            field=models.IntegerField(
                blank=True,
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                null=True,
                verbose_name="解答番号5",
            ),
        ),
    ]
