# Generated by Django 4.1.4 on 2023-01-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0004_alter_quiz_answer2_alter_quiz_answer3_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="answer1",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="answer2",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="answer3",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="answer4",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="answer5",
        ),
        migrations.AddField(
            model_name="quiz",
            name="is_option1_correct",
            field=models.BooleanField(default=False, verbose_name="選択肢1は正解か"),
        ),
        migrations.AddField(
            model_name="quiz",
            name="is_option2_correct",
            field=models.BooleanField(default=False, verbose_name="選択肢2は正解か"),
        ),
        migrations.AddField(
            model_name="quiz",
            name="is_option3_correct",
            field=models.BooleanField(default=False, verbose_name="選択肢3は正解か"),
        ),
        migrations.AddField(
            model_name="quiz",
            name="is_option4_correct",
            field=models.BooleanField(default=False, verbose_name="選択肢4は正解か"),
        ),
        migrations.AddField(
            model_name="quiz",
            name="is_option5_correct",
            field=models.BooleanField(default=False, verbose_name="選択肢5は正解か"),
        ),
    ]
